//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.reader.service.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.reader.service.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;target&quot;: &quot;denton&quot;,
        ///		&quot;payload&quot;:[
        ///			&quot;{&quot;,
        ///			&quot;&apos;state&apos;: &apos;tx&apos;,&quot;,
        ///			&quot;&apos;county&apos;: {&quot;,
        ///			&quot;&apos;name&apos;: &apos;denton&apos;,&quot;,
        ///			&quot;&apos;value&apos;: 26730&quot;,
        ///			&quot;},&quot;,
        ///			&quot;&apos;details&apos;: [&quot;,
        ///			&quot;{&quot;,
        ///			&quot;&apos;name&apos;: &apos;Court Type&apos;,&quot;,
        ///			&quot;&apos;text&apos;: &apos;All County Courts&apos;,&quot;,
        ///			&quot;&apos;value&apos;: &apos;9&apos;&quot;,
        ///			&quot;},&quot;,
        ///			&quot;{&quot;,
        ///			&quot;&apos;name&apos;: &apos;Case Type&apos;,&quot;,
        ///			&quot;&apos;text&apos;: &apos;JP And County Courts&apos;,&quot;,
        ///			&quot;&apos;value&apos;: &apos;0&apos;&quot;,
        ///			&quot;}&quot;,
        ///			&quot;],&quot;,
        ///			&quot;&apos;start&apos;: 1696118400000,&quot;,
        ///			&quot;&apos;end&apos;: 1696636800000&quot;,
        ///			&quot;}&quot;
        ///		]
        ///	},
        ///	{
        ///		&quot;target&quot;: &quot;harris&quot;,
        ///		&quot;payload&quot;:[
        ///		 [rest of string was truncate....
        /// </summary>
        internal static string requestsample_json {
            get {
                return ResourceManager.GetString("requestsample_json", resourceCulture);
            }
        }
    }
}
