name: "CD : Publish and Deploy"

on:
  pull_request:
    types: [labeled]
    branches:
      - "releases"


env:
  SOLUTION_NAME: ${{ github.workspace }}\src\legallead.reader.sln
  PROJECT_NAME: ${{ github.workspace }}\src\worker\legallead.reader.service.csproj
  PROJECT_TITLE: "legallead.reader.service"
  PUBLISH_DIR: ${{ github.workspace }}\publish
  NET_VERSION: "8.0.x"
  NUGET_CERT_REVOCATION_MODE: offline

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Build Version
        shell: bash
        run: |
            echo "BUILD_VERSION=${{format('{0}.{1}', vars.LEGALLEAD_READER_PREFIX, github.run_number)}}" >> $GITHUB_ENV

      - name: Set ZipFile Name
        shell: bash
        run: |
            echo "ZIPFILE_NAME=${{format('{0}-{1}.zip', env.PROJECT_TITLE, env.BUILD_VERSION )}}" >> $GITHUB_ENV

      - name: Calculate Release Title
        shell: pwsh
        run: |
            & ./util/x-pipeline-reader-release-title.ps1

      - name: Update README
        shell: pwsh
        run: |
            & ./util/x-pipeline-update-release-notes.ps1 -version "${{ env.BUILD_VERSION }}"

      - run: dotnet restore ${{ env.SOLUTION_NAME }}
        id: dotnet-restore
        name: DotNet Restore

      - run: dotnet publish ${{ env.PROJECT_NAME }} --no-restore -c Release -o ${{ env.PUBLISH_DIR }}
        id: dotnet-publish
        name: DotNet Publish
        
      - uses: actions/upload-artifact@v4
        with:
          name: reader
          path: ${{ github.workspace }}/publish/**